export const APP_ROUTES = {
  HOME: '/',
  FEATURES: '/features',
  PRICING: '/pricing',
  BLOG: '/blog',
  FAQ: '/faq',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',
  PRACTICE: '/dashboard/practice',
  SCHEDULE: '/dashboard/schedule',
  PROFILE: '/dashboard/profile',
  PROGRESS: '/dashboard/progress',
  AI_TUTOR: '/dashboard/ai-tutor',
  SETTINGS: '/dashboard/settings',
  ONBOARDING: '/onboarding',
  ADMIN_DASHBOARD: '/admin',
  TEACHER_DASHBOARD: '/teacher',
} as const;
